# Generated by Django 2.1.1 on 2019-02-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sensor_limits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Max_Angle', models.IntegerField()),
                ('Max_Discrete_Temperature', models.IntegerField()),
                ('Min_Discrete_Temperature', models.IntegerField()),
                ('Max_Integrated_Temperature', models.IntegerField()),
                ('Min_Integrated_Temperature', models.IntegerField()),
                ('Max_Acceleration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sensor_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp_discrete', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temp_integrated', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gyro_x', models.IntegerField()),
                ('gyro_y', models.IntegerField()),
                ('gyro_z', models.IntegerField()),
                ('accel_x', models.DecimalField(decimal_places=3, max_digits=4)),
                ('accel_y', models.DecimalField(decimal_places=3, max_digits=4)),
                ('accel_z', models.DecimalField(decimal_places=3, max_digits=4)),
                ('angle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='violation_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('angle', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
