# Generated by Django 2.1.1 on 2019-02-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_violation_values_accel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_limits',
            name='current',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
